apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-clickhouse-task
spec:
  params:
    - name: repository-url
      type: string
      description: The URL of the Git repository to clone
    - name: revision
      type: string
      description: The Git revision to checkout
      default: "master"
  workspaces:
    - name: source
      description: The workspace to store the cloned repository
    - name: build-output
      description: The workspace to store build artifacts
  steps:
    - name: clone
      image: "alpine/git:v2.30.2"
      script: |
        git clone $(params.repository-url) $(workspaces.source.path) --branch $(params.revision)
    - name: build
      image: "your-build-image"  # Replace with the appropriate build image
      script: |
        cd $(workspaces.source.path)/docker/packager/binary-builder
        ./build.sh
      volumeMounts:
        - name: build-output
          mountPath: /output
  volumes:
    - name: build-output
      emptyDir: {}  # Use PVC if needed
