apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clickhouse-build-pipeline
spec:
  params:
    - name: git-repo-url
      type: string
      default: https://github.com/ClickHouse/ClickHouse.git
    - name: git-revision
      type: string
      default: master
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: source
          workspace: source
    - name: build-clickhouse
      runAfter:
        - clone-repo
      taskRef:
        name: build-clickhouse
      params:
        - name: source-dir
          value: $(workspaces.source.path)
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source
