apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: repository-url
      type: string
      description: The URL of the Git repository to clone
    - name: revision
      type: string
      description: The Git revision (branch, tag, commit SHA) to checkout
      default: "master"
  workspaces:
    - name: output
      description: Git repository will be cloned into this workspace
  steps:
    - name: clone
      image: "alpine/git:v2.30.2"
      script: |
        #!/bin/sh
        set -e
        git clone $(params.repository-url) $(workspaces.output.path) --branch $(params.revision)

