apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-clickhouse-pipeline-run
spec:
  pipelineRef:
    name: clone-clickhouse-pipeline
  params:
    - name: repository-url
      value: https://github.com/ks-sharath/ClickHouse-pipeline.git
    - name: revision
      value: master
  workspaces:
    - name: shared-workspace
      emptyDir: {}

