apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-clickhouse-pipeline
spec:
  params:
    - name: source-dir
      type: string
      default: "."  # Adjust as needed
    - name: repository-url
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-task
      params:
        - name: repository-url
          value: "$(params.repository-url)"
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-clickhouse
      taskRef:
        name: build-clickhouse-task
      runAfter:
        - clone-repo
      params:
        - name: source-dir
          value: "$(params.source-dir)"
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: build-output
          workspace: shared-workspace

