apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clickhouse-build-pipeline-run
spec:
  pipelineRef:
    name: build-clickhouse-pipeline
  params:
    - name: source-dir
      value: "."
    - name: repository-url
      value: "https://github.com/ks-sharath/ClickHouse-pipeline.git"
  workspaces:
    - name: shared-workspace
      emptyDir: {}
